kind: pipeline
name: default

steps:
- name: setup
  image: node
  commands:
  - npm install
  - npm install zapier-platform-cli
- name: lint
  image: node
  commands:
  - npm run lint:js
- name: test
  image: node
  commands:
  - npm run test
- name: validate
  image: node
  commands:
  - $(npm bin)/zapier validate
- name: publish
  image: node
  environment:
    ZAPIER_DEPLOY_KEY:
      from_secret: zapier_deploy_key
  commands:
  - $(npm bin)/zapier push
  #- $(npm bin)/zapier promote $DRONE_TAG | cut -d "v" -f2
  when:
    ref:
      - refs/tags/v*

trigger:
  event:
  - push
  - pull_request
