kind: pipeline
name: default

steps:
- name: setup
  image: node
  commands:
  - npm install
  - npm install zapier-platform-cli
- name: lint
  image: node
  commands:
  - npm run lint:js
- name: test
  image: node
  commands:
  - npm run test
- name: validate
  image: node
  commands:
  - $(npm bin)/zapier validate

trigger:
  event:
  - push
  - pull_request
