kind: pipeline
name: default

steps:
- name: setup
  image: node
  commands:
  - npm install
- name: lint
  image: node
  commands:
  - npm run lint:js
- name: test
  image: node
  commands:
  - npm run test

trigger:
  event:
  - push
  - pull_request
